### ISSUE TITLE
[Proposal] Move `helix-onchain/filecoin` to `filecoin-project` org

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/actors-utils#234]
### Description:
Opening a proposal for moving the `helix-onchain/filecoin` repository to the `filecoin-project` organization as long as the current maintainers are fine with it.

### Reasons:
- Moving the repository to the `filecoin-project` organization will ensure it receives the necessary attention and updates, and provide a more sustainable environment for long-term maintenance and support.

### Notes
- If we proceed with the transfer, we will need to rename the repository. This is necessary because there is already a repository named filecoin in the filecoin-project organization.

**Comment by rvagg** [comment]
We could call it "onchain" or "filecoin-onchain".

**Comment by alexytsu** [comment]
On Helix's side, we're happy for this to move to whichever organisation or repo that's most convenient for long term maintenance and support.

**Comment by anorth** [comment]
I think we can find a better name. "Helix" is the discriminating part of the original name that would preserve credit to the primary authors. Or a more descriptive something like "actors-tokens" or "actors-frcs"?

**Comment by BigLep** [comment]
I think we just need a decision here, and my sense is that no on cares too much here (but correct me if I have that wrong).  This is a bit time sensitive because we're hoping to have IPDX help with some release automation this week (week of 2024-07-15).  It would make sense to do that in the filecoin-project org.

I vote for a more descriptive name for what this repo houses rather than its origin/authorship.  

Given the repo has some utilities (frc42_dispatch, frc46_token) and tokens (frc53_nft, frc46_factory_token), what about going with a broad/generic name like "actors-utils".  I realize though that has the potential issue of vagueness in the worst case leading to a package that becomes a catch-all for miscellaneous functions.  

To make sure a decision gets made by **EOD 2024-07-17**, folks can case their vote with an emoji response:
😄: actors-utils
🎉 : actors tokens
🚀 : actors-frcs

Add another emoji if you want something else to be considered (but let's act quick!)

@alexytsu (or another repo owner), can you please proactively give owner permissions to @rjan90 or me so we can self-service execute on the move later this week?

**Comment by rvagg** [comment]
👍 I approve, `actors-utils` is fine, make it so

**Comment by BigLep** [comment]
If I don't hear any objections, I will move/rename this repo to filecoin-project/actors-utils when I start work 2024-07-18 Pacific time morning.  (@rjan90 feel free to execute on it sooner.)

**Comment by BigLep** [comment]
Also, @rjan90 , is there anyone that is going to be caught offf guard by this change beyond those who have been involved with this issue?  (I'm wondering if we need to communicate special anywhere - or are GitHub redirects good enough?)

**Comment by BigLep** [comment]
Repo has been migrated: https://github.com/filecoin-project/actors-utils

I'll close this issue, but please reopen @rjan90 or others if we need to do more comms about this.

**Comment by BigLep** [comment]
Also, for the record, there was a fork of this repo at https://github.com/filecoin-project/filecoin-actor-utils :)  That is good validation for the name we chose.  (I will get that fork archived soon...)
